
on:
  workflow_dispatch

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        npm install
        npm run build
        ls
    - name: Copy Build Folder
      uses: appleboy/scp-action@master
      with:
        host: cuencador.com
        username: deploy
        port: 50001
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        strip_components: 1
        source: "build/"
        target: "/var/cuencador/www/cuencador-kit"
    - name: Copy package.json
      uses: appleboy/scp-action@master
      with:
        host: cuencador.com
        username: deploy
        port: 50001
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        strip_components: 0
        source: "package.json"
        target: "/var/cuencador/www/cuencador-kit"  
    - name: Run npm -i
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /var/cuencador/www/cuencador-kit && npm -i
        host: cuencador.com
        port: 50001
        username: deploy
        privateKey: ${{ secrets.DEPLOY_SSH_KEY}}

    # - name: Execute test Script
    #   run: ssh -p {{DEPLOY_SSH_PORT}} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST}} bash test.sh

