
on:
  workflow_dispatch

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ env.NODE_VERSION }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}
    # - name: npm install, build
    #   run: |
    #     npm install
    #     npm run build
    - name: Install SSH key of bastion
      uses: shimataro/ssh-key-action@v2
      with:
      key: ${{ secrets.SSH_CUENCADOR_LINODE }}
      name: id_rsa-bastion
      known_hosts: ${{ secrets.KNOWN_HOSTS }}
      # config: |
      #   Host bastion
      #     HostName xxx.xxx.xxx.xxx
      #     User user-of-bastion
      #     IdentityFile ~/.ssh/id_rsa-bastion
      # if_key_exists: replace
    -name: test ssh
    -run: scp ./package.json target:Pictures/

