
on:
  workflow_dispatch

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - uses: actions/checkout@v2
    # - name: Use Node.js ${{ env.NODE_VERSION }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}
    # - name: npm install, build
    #   run: |
    #     npm install
    #     npm run build

    - name: Create tar from build output
      run: |
        ls
    # tar -cvf deploy.tar ./package.json    
    - name: Install SSH key of cuencador
      uses: appleboy/scp-action@master
      # with:
      #   host: ${{ secrets.DEPLOY_HOST }}
      #   username: ${{ secrets.DEPLOY_USER }}
      #   port: ${{ secrets.DEPLOY_SSH_PORT }}
      #   key: ${{ secrets.DEPLOY_SSH_KEY_LINODE }}
      #   source: "src/"
      #   target: "src"  
      with:
        host: cuencador.com
        username: deploy
        port: 50001
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: "src/"
        target: "src"  
    # - name: Execute test Script
    #   run: ssh -p {{DEPLOY_SSH_PORT}} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST}} bash test.sh

