/**
 * @param {import('@sveltejs/kit').Request} request
 * @param {any} context
 * @returns {import('@sveltejs/kit').Response}
 */
import { googleConfig } from '$lib/config/login.config'
import { getSession } from '$lib/config/database.config'

let client = null;

export async function get(request, context) {
    let client = googleConfig.googleClient

    async function verify() {
        const ticket = await client.verifyIdToken({
            idToken: request.query.get("id_token"),
            audience: googleConfig.GoogleClientId,  // Specify the CLIENT_ID of the app that accesses the backend
        });
        return ticket.getPayload();
    }
    let res = await verify().catch(console.error);

    // TODO: Catch Errors.
    let sess = await getSession()
    let x = await sess.getSchema('Cuencador')
        .getTable('Users')
        .insert(['social_key', 'name', 'email'])
        .values(`G${res.sub}`, res.name, res.email)
        .execute();

    console.log(`Autogenerated Id: ${x.getAutoIncrementValue()}`);

    sess.close()

    return {
        body: JSON.stringify({ email: res['email'], email_verified: res['email_verified'], name: res['name'] }),
    }
}

